import React from "react";

interface CertificatePDFProps {
  certificateId: string;
  projectName: string;
  quantity: number;
  date: string;
}

const CertificatePDF: React.FC<CertificatePDFProps> = ({
  certificateId,
  projectName,
  quantity,
  date,
}) => {
  return (
    <div
      style={{
        width: "210mm",
        height: "297mm",
        padding: "40px",
        fontFamily: "Arial, sans-serif",
        background: "#ffffff",
        border: "12px solid #10b981",
      }}
    >
      <h1 style={{ textAlign: "center", marginBottom: 40 }}>
        🌱 Carbon Credit Retirement Certificate
      </h1>

      <p style={{ fontSize: 16, textAlign: "center", marginBottom: 30 }}>
        This certifies that
      </p>

      <h2 style={{ textAlign: "center", marginBottom: 20 }}>
        {quantity} tCO₂e
      </h2>

      <p style={{ textAlign: "center", fontSize: 16 }}>
        carbon credits from the project
      </p>

      <h3 style={{ textAlign: "center", marginBottom: 40 }}>
        “{projectName}”
      </h3>

      <p style={{ textAlign: "center" }}>
        have been permanently retired on
      </p>

      <h4 style={{ textAlign: "center", marginBottom: 40 }}>{date}</h4>

      <hr />

      <div style={{ marginTop: 40 }}>
        <p>
          <strong>Certificate ID:</strong> {certificateId}
        </p>
        <p>
          <strong>Status:</strong> Permanently Retired
        </p>
      </div>

      <p
        style={{
          position: "absolute",
          bottom: 40,
          width: "100%",
          textAlign: "center",
          fontSize: 12,
          color: "#666",
        }}
      >
        Generated by Offset Platform • Verifiable Retirement Record
      </p>
    </div>
  );
};

export default CertificatePDF;
